SCRIPTS = [
    {
        "topic": "Automatiza el seguimiento de clientes",
        "script": "Estás perdiendo clientes que ya te habían dicho que sí. No porque tu servicio sea malo. Sino porque no les escribiste a tiempo. Un fontanero en Madrid cerraba 2 de cada 10 presupuestos. Ahora cierra 7. Solo cambió una cosa: cuando alguien pide precio, recibe un WhatsApp en 30 segundos. Automático. Él no toca nada. ¿Cuántos clientes has perdido tú esta semana? Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["CLIENTES PERDIDOS", "30 SEGUNDOS", "7 DE CADA 10", "CIERRA MÁS"],
        "hashtags": ["#automatizacion", "#gestionclientes", "#pymesespana", "#ventas", "#ziautomate"],
        "engagement_question": "¿Cuántos clientes has perdido esta semana por no hacer seguimiento a tiempo?",
    },
    {
        "topic": "Trabajas más horas que tus empleados",
        "script": "Tienes un negocio pero sigues siendo tu empleado más barato. Confirmando citas a mano. Respondiendo las mismas preguntas de siempre. Introduciendo datos en Excel. Una dentista en Valencia hacía eso 2 horas al día. Cuarenta horas al mes regaladas a tareas de robot. Con una automatización ese tiempo desapareció. Sin contratar a nadie. Sin cambiar nada de lo que ya usaba. ¿Cuántas horas estás regalando tú? Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["40 HORAS/MES", "TRABAJO DE ROBOT", "SIN CONTRATAR", "TIEMPO LIBRE"],
        "hashtags": ["#automatizacion", "#productividadempresarial", "#pymesdigitales", "#trabajosmart", "#ziautomate"],
        "engagement_question": "¿Cuántas horas a la semana dedicas a tareas que podría hacer una máquina?",
    },
    {
        "topic": "El negocio que responde primero gana siempre",
        "script": "Todo el mundo te dice que atiendas bien a tus clientes. Nadie te dice que si tardas más de 5 minutos en responder, ya perdiste esa venta. El 78% de las ventas va al negocio que contesta primero. No al mejor. Al más rápido. Una inmobiliaria en Málaga perdía 30 consultas al mes porque cerraban a las 8. Pusimos IA que responde al instante las 24 horas. Ese mes cerraron 4 operaciones más. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["78% AL PRIMERO", "24/7 RESPONDE", "4 OPERACIONES MÁS", "IA TRABAJA"],
        "hashtags": ["#automatizacion", "#atencioncliente", "#inteligenciaartificial", "#pymesespana", "#ziautomate"],
        "engagement_question": "¿En cuánto tiempo respondes tú normalmente a los contactos nuevos?",
    },
    {
        "topic": "Publica en redes todos los días sin esfuerzo",
        "script": "Dentro de 6 meses el negocio de tu sector que publique todos los días en redes va a tener el doble de clientes que el que no publica. ¿Cuál vas a ser tú? Una tienda de ropa en Sevilla publicaba una vez a la semana. Ahora publica todos los días. Con IA generan en 20 minutos el contenido de la semana entera. En 3 meses triplicaron seguidores y empezaron a recibir pedidos directamente del perfil. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["CADA DÍA", "20 MINUTOS", "3X SEGUIDORES", "PILOTO AUTO"],
        "hashtags": ["#marketingdigital", "#instagramnegocios", "#contenidodigital", "#redessociales", "#ziautomate"],
        "engagement_question": "¿Cuántos días llevas sin publicar en tus redes?",
    },
    {
        "topic": "Tu formulario web está regalando clientes",
        "script": "El 80% de las personas que rellenan un formulario en tu web y no reciben respuesta en 5 minutos se van con tu competencia. Para siempre. ¿Cuántos formularios has recibido esta semana? ¿En cuántos tardaste más de 5 minutos? Un electricista en Barcelona conectó su web a WhatsApp. Ahora cualquier formulario recibe respuesta en 30 segundos con el nombre del cliente y los próximos pasos. Sus presupuestos aceptados se triplicaron. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["80% SE PIERDEN", "5 MINUTOS", "3X PRESUPUESTOS", "RESPUESTA AUTO"],
        "hashtags": ["#automatizacion", "#marketingdigital", "#ventadigital", "#pymesespana", "#ziautomate"],
        "engagement_question": "¿Cuánto tardas en responder los formularios que llegan a tu web?",
    },
    {
        "topic": "3 automatizaciones que te devuelven 20 horas al mes",
        "script": "Voy a darte las 3 automatizaciones que más tiempo ahorran en cualquier negocio. Una: respuesta automática a contactos nuevos en menos de 2 minutos. Dos: recordatorio de cita 24 horas antes. Tres: seguimiento a presupuestos sin respuesta a los 2 días. Con estas tres, la mayoría de negocios recuperan entre 15 y 25 horas al mes. Una semana entera de trabajo que puedes dedicar a lo que realmente importa. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["3 CLAVES", "20 HORAS/MES", "2 SEMANAS RESULT.", "EMPIEZA HOY"],
        "hashtags": ["#automatizacion", "#productividadempresarial", "#pymesdigitales", "#transformaciondigital", "#ziautomate"],
        "engagement_question": "¿Cuál de estas tres automatizaciones te ahorraría más tiempo a ti?",
    },
    {
        "topic": "n8n conecta todo tu negocio sin programadores",
        "script": "Tienes web, WhatsApp, email, Excel e Instagram. Y todos funcionan por separado. Eso son horas perdidas cada día pasando datos de un sitio a otro a mano. n8n conecta todo automáticamente sin una línea de código. Una academia de idiomas tardaba 15 minutos en apuntar a cada alumno nuevo en 4 sistemas distintos. Ahora cuando alguien paga, todo se actualiza solo en 10 segundos. Nadie toca nada. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["TODO CONECTADO", "10 SEGUNDOS", "SIN CÓDIGO", "N8N"],
        "hashtags": ["#n8n", "#automatizacion", "#nocode", "#integraciones", "#ziautomate"],
        "engagement_question": "¿Cuántas aplicaciones tienes abiertas ahora mismo que no se hablan entre sí?",
    },
    {
        "topic": "Tu web tiene visitas pero nadie te llama",
        "script": "El 97% de la gente que entra en tu web se va sin dejar sus datos. Para siempre. El problema no es el diseño. Es que no tienes nada que los retenga. Lo que montamos: un chat de IA que aparece cuando llevan 30 segundos mirando un servicio, hace 2 preguntas y recoge su contacto. Te lo manda con un resumen de lo que quieren. Una óptica en Zaragoza captura ahora 40 leads al mes que antes perdía sin dejar rastro. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["97% SE VAN", "40 LEADS/MES", "IA CAPTURA", "NUNCA MÁS"],
        "hashtags": ["#marketingdigital", "#generacionleads", "#embudo", "#pymesespana", "#ziautomate"],
        "engagement_question": "¿Sabes cuántas visitas recibe tu web al mes y cuántas acaban dejando sus datos?",
    },
    {
        "topic": "Deja de perseguir tus propios cobros",
        "script": "No hay nada más humillante en un negocio que perseguir tus propios cobros. Escribir el mismo email de recordatorio una y otra vez. Esperar. Volver a escribir. Un diseñador gráfico perdía 3 horas a la semana solo en esto. Ahora la factura se genera sola cuando cierra un proyecto y manda recordatorios automáticos si no pagan. Sin que él toque nada. Recuperó 12 horas al mes y dejó de sentirse mal pidiendo lo que es suyo. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["12 HORAS/MES", "COBROS AUTO", "SIN PERSEGUIR", "FACTURA SOLA"],
        "hashtags": ["#automatizacion", "#facturacion", "#autonomos", "#gestionempresarial", "#ziautomate"],
        "engagement_question": "¿Cuánto tiempo pierdes al mes persiguiendo cobros o enviando recordatorios de pago?",
    },
    {
        "topic": "Las inmobiliarias que no usan IA pierden ventas esta noche",
        "script": "Un cliente busca piso a las 11 de la noche. Te escribe. Tú estás durmiendo. Mañana le contestas. Para entonces ya habló con 3 agencias más. Esta escena pasa cada noche en miles de agencias de España. Una en Málaga perdía 4 operaciones al mes así. Pusimos IA que responde al instante, agenda visitas y solo avisa al agente cuando hay que cerrar. El primer mes recuperaron las 4 operaciones que antes se perdían. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["11PM RESPONDE", "4 OPERACIONES", "AGENDA VISITAS", "0 PERDIDAS"],
        "hashtags": ["#inmobiliaria", "#automatizacion", "#inteligenciaartificial", "#proptech", "#ziautomate"],
        "engagement_question": "¿A qué hora llegan los últimos mensajes a tu negocio y quién los responde?",
    },
    {
        "topic": "Make: automatiza tu negocio sin saber programar",
        "script": "Dos personas gestionando pedidos a mano. Copiando datos entre plataformas. Cometiendo errores. Ese era el día a día de un ecommerce de productos naturales. Hoy una sola persona gestiona el doble de pedidos. ¿Qué cambió? Make. Cuando alguien compra, automáticamente se actualiza el stock, el almacén recibe el pedido, el cliente recibe el tracking y queda apuntado en el CRM. Todo en 3 segundos. Sin tocar nada. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["3 SEGUNDOS", "DOBLE PEDIDOS", "SIN ERRORES", "MAKE"],
        "hashtags": ["#makeautomation", "#automatizacion", "#nocode", "#productividadempresarial", "#ziautomate"],
        "engagement_question": "¿Cuántos pasos manuales tiene tu proceso de pedidos o ventas ahora mismo?",
    },
    {
        "topic": "Tu competencia ya usa IA y tú todavía no",
        "script": "Tu competencia tomó una decisión hace 6 meses que tú todavía no has tomado. No son grandes empresas. Son autónomos y pymes exactamente como tú. Cada mes que pasa la diferencia es mayor. Captan más leads. Atienden mejor. Cierran más. La buena noticia es que todavía estás a tiempo. Pero el tiempo se acaba. Un sistema básico de automatización se paga solo en el primer mes. ¿Cuánto más vas a esperar? Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["6 MESES TARDE", "TODAVÍA A TIEMPO", "MES 1 PAGADO", "DECÍDETE YA"],
        "hashtags": ["#inteligenciaartificial", "#transformaciondigital", "#pymesespana", "#futurodigital", "#ziautomate"],
        "engagement_question": "¿Qué es lo primero que automatizarías en tu negocio si pudieras empezar hoy?",
    },
    {
        "topic": "Automatiza las citas de tu negocio esta semana",
        "script": "Cada cita que no aparece es dinero perdido, tiempo perdido y una rabia enorme. Una peluquería en Valencia tenía un 30% de no-shows cada semana. Treinta por ciento de la agenda vacía sin avisar. Lo automatizamos: WhatsApp automático 24 horas antes con botón de confirmar o cancelar. Si cancela, el hueco se rellena solo con alguien de lista de espera. No-shows bajaron al 5%. Veinticinco por ciento más de ingresos sin contratar a nadie. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["30% NO-SHOWS", "LISTA DE ESPERA", "+25% INGRESOS", "ESTA SEMANA"],
        "hashtags": ["#automatizacion", "#gestioncitas", "#pymesespana", "#reservasautomaticas", "#ziautomate"],
        "engagement_question": "¿Cuántas citas o reservas no aparecen al mes en tu negocio?",
    },
    {
        "topic": "Tu CRM está vacío y sabes por qué",
        "script": "Te voy a decir por qué tu CRM está vacío aunque hayas pagado por él. Porque actualizarlo a mano después de cada conversación, cada cita y cada venta es un infierno que nadie hace. Lo que nosotros montamos hace que se actualice solo. Cliente escribe por WhatsApp: entra en el CRM. Reserva una cita: queda registrado. Compra: se actualiza. Tú siempre sabes en qué punto está cada cliente sin haber tocado nada. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["CRM VACÍO", "AUTO-ACTUALIZA", "SIEMPRE AL DÍA", "SIN TOCAR NADA"],
        "hashtags": ["#crm", "#automatizacion", "#gestionclientes", "#pymesdigitales", "#ziautomate"],
        "engagement_question": "¿Cuándo fue la última vez que actualizaste tu CRM de forma manual?",
    },
    {
        "topic": "Tu negocio generando clientes mientras duermes",
        "script": "Imagina levantarte mañana y tener 5 mensajes de personas que quieren contratarte. Sin haber hecho nada la noche anterior. Eso no es un sueño. Es el día a día de un consultor financiero en Madrid. Un sistema responde sus consultas a las 3 de la mañana, captura el contacto y programa una llamada para el día siguiente. Cuando él se despierta, solo tiene que cerrar. Sus mañanas ya no son para buscar clientes. Son para atenderlos. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["5 LEADS/NOCHE", "3AM RESPONDE", "MIENTRAS DUERMES", "SOLO CIERRA"],
        "hashtags": ["#automatizacion", "#negocioonline", "#inteligenciaartificial", "#emprendedordigital", "#ziautomate"],
        "engagement_question": "¿A qué hora fue el último mensaje que llegó a tu negocio sin que nadie lo atendiera?",
    },
    {
        "topic": "El restaurante que casi cierra por los no-shows",
        "script": "Un restaurante en Barcelona llegó a tener el 30% de sus mesas vacías un sábado por la noche. Reservas que no aparecieron. Sin avisar. Sin pagar. Automatizamos todo: confirmación por WhatsApp 48 horas antes, lista de espera automática si cancela, solicitud de reseña en Google después de la visita. No-shows bajaron al 5%. Reseñas subieron de 4.1 a 4.7 en dos meses. El dueño no tuvo que hacer nada para montarlo. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["30% VACÍAS", "4.7 ESTRELLAS", "LLENO SIEMPRE", "-85% NO-SHOWS"],
        "hashtags": ["#restaurante", "#automatizacion", "#hosteleria", "#gestionreservas", "#ziautomate"],
        "engagement_question": "¿Cuántas reservas fantasma tienes al mes en tu negocio?",
    },
    {
        "topic": "Cómo generar contenido con IA todos los días",
        "script": "El algoritmo de Instagram premia la constancia por encima de todo. Y la constancia es exactamente lo que más cuesta cuando llevas un negocio solo. Una clínica estética en Madrid publicaba una vez a la semana. Ahora publica todos los días. Con IA generan en 20 minutos el contenido de la semana entera: textos, hashtags e ideas para vídeo. Lo programan y se publica solo. En 3 meses doblaron seguidores y empezaron a recibir consultas directamente de Instagram. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["20 MINUTOS", "TODOS LOS DÍAS", "2X SEGUIDORES", "CONSTANCIA"],
        "hashtags": ["#inteligenciaartificial", "#marketingdigital", "#contenidodigital", "#instagramnegocios", "#ziautomate"],
        "engagement_question": "¿Cuántos días llevas sin publicar en Instagram?",
    },
    {
        "topic": "Sincroniza tu tienda online con tu almacén",
        "script": "Vender algo que no tienes en stock es una de las peores experiencias que puede tener un cliente. Genera devoluciones, reseñas de una estrella y no vuelven nunca. Si gestionas el stock a mano en varios canales esto te va a pasar antes o después. La solución: sincronización automática en tiempo real. Vendes en tu web, en Amazon, en Instagram. El stock se actualiza solo en todos lados en segundos. Un ecommerce de moda redujo sus incidencias un 94% el primer mes. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["TIEMPO REAL", "-94% ERRORES", "TODOS LOS CANALES", "CERO MANUAL"],
        "hashtags": ["#ecommerce", "#automatizacion", "#tiendaonline", "#ventaonline", "#ziautomate"],
        "engagement_question": "¿Gestionas el stock de tu tienda de forma manual en varios canales?",
    },
    {
        "topic": "La clínica que dejó de perder 640 euros al mes",
        "script": "Ocho citas perdidas al mes. A 80 euros la sesión. Son 640 euros tirados cada mes. Eso es lo que perdía una psicóloga en Madrid por cancelaciones de última hora que no podía rellenar. Lo automatizamos: recordatorio por WhatsApp 72 horas antes, otro 24 horas antes, otro el mismo día. Si cancela con tiempo el hueco se rellena solo con alguien de lista de espera. Las citas perdidas bajaron un 70%. Ella no tocó nada. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["640€/MES PERDIDOS", "-70% CANCELACIONES", "LISTA DE ESPERA", "RECUPERA TODO"],
        "hashtags": ["#salud", "#automatizacion", "#gestioncitas", "#clinicadigital", "#ziautomate"],
        "engagement_question": "¿Cuántas citas pierdes al mes por cancelaciones de última hora?",
    },
    {
        "topic": "Envía propuestas en 5 minutos y cierra el doble",
        "script": "El 50% de las ventas van al proveedor que responde primero. No al mejor. No al más barato. Al más rápido. Y si tardas 2 horas en enviar una propuesta después de hablar con un cliente, ya estás perdiendo contra alguien que la envía en 5 minutos. Lo que montamos: rellenas 5 campos, la propuesta se genera sola con tu logo y tus precios, y se envía automáticamente con enlace para firmar. Un consultor pasó de cerrar 3 de cada 10 a cerrar 6. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["50% AL PRIMERO", "5 MINUTOS", "6 DE CADA 10", "FIRMA DIGITAL"],
        "hashtags": ["#automatizacion", "#ventas", "#cierreventas", "#pymesespana", "#ziautomate"],
        "engagement_question": "¿Cuánto tardas en enviar una propuesta después de hablar con un cliente?",
    },
    {
        "topic": "Automatización e IA: la combinación que lo cambia todo",
        "script": "La gente que cree que la IA lo va a hacer todo sola está equivocada. Y la que cree que la automatización es suficiente también. Lo más potente es combinar las dos. La IA entiende y decide. La automatización ejecuta. Ejemplo real: la IA lee un email de un cliente, detecta que quiere un presupuesto, y la automatización lo genera y envía sin que tú intervengas. El cliente recibe respuesta en segundos. Tú no has tocado nada. Eso es lo que montamos. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["IA + AUTOMATIZA", "ENTIENDE Y DECIDE", "SIN INTERVENIR", "ZIAUTOMATE"],
        "hashtags": ["#inteligenciaartificial", "#automatizacion", "#transformaciondigital", "#ia", "#ziautomate"],
        "engagement_question": "¿Usas automatización, IA, o todavía ninguna de las dos en tu negocio?",
    },
    {
        "topic": "El presupuesto en silencio que todavía puedes recuperar",
        "script": "Enviaste el presupuesto. Pasaron 3 días. Silencio. ¿Le escribes tú y pareces desesperado? ¿O esperas y pierdes la venta? Hay una tercera opción. Un sistema que a las 48 horas manda automáticamente un mensaje preguntando si tiene dudas. A los 5 días, otro con urgencia suave. Sin que tú escribas nada. Sin que parezca que estás persiguiéndole. El 30% de los presupuestos que antes se perdían así se recuperan con esto. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["3 DÍAS SILENCIO", "+30% RECUPERADOS", "48H AUTOMÁTICO", "DINERO QUE VUELVE"],
        "hashtags": ["#automatizacion", "#ventas", "#seguimientoclientes", "#pymesespana", "#ziautomate"],
        "engagement_question": "¿Haces seguimiento a los presupuestos que envías o simplemente esperas respuesta?",
    },
    {
        "topic": "Del caos total al negocio organizado con Airtable",
        "script": "Si tienes clientes en Excel, proyectos en WhatsApp, tareas en papel y facturas en otro sitio, no tienes un negocio organizado. Tienes un caos que un día va a costarte un cliente importante. Airtable centraliza todo y lo conecta con el resto de herramientas que ya usas. Una agencia de eventos gestiona 50 eventos al año desde un solo sitio. Cuando entra un cliente nuevo, todo el flujo de trabajo arranca solo. Sin reuniones de coordinación. Sin información perdida. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["DEL CAOS AL ORDEN", "50 EVENTOS", "TODO EN UN SITIO", "AIRTABLE"],
        "hashtags": ["#airtable", "#automatizacion", "#gestionempresarial", "#nocode", "#ziautomate"],
        "engagement_question": "¿Dónde tienes guardada ahora mismo la información de tus clientes?",
    },
    {
        "topic": "Zapier, Make o n8n: cuál es para tu negocio",
        "script": "Tres herramientas. Una pregunta. ¿Cuál te conviene a ti? Zapier: el más fácil y el más caro. Ideal si quieres empezar hoy sin complicaciones. Make: el equilibrio perfecto. Visual, potente y precio razonable. El que recomiendo para la mayoría de pymes. n8n: control total y el más barato a largo plazo. Para quien quiere independencia absoluta. Lo importante no es la herramienta. Es el sistema que montas con ella. ¿Cuál es el tuyo? Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["ZAPIER", "MAKE", "N8N", "¿CUÁL ES EL TUYO?"],
        "hashtags": ["#zapier", "#makeautomation", "#n8n", "#automatizacion", "#ziautomate"],
        "engagement_question": "¿Cuál usas tú: Zapier, Make, n8n o ninguno todavía?",
    },
    {
        "topic": "IA que atiende clientes mejor que muchos empleados",
        "script": "Esto va a sonar raro: los clientes de una academia online dijeron que la atención había mejorado justo después de que la academia redujera su equipo de soporte a la mitad. ¿Qué pasó? Pusieron un bot de IA entrenado con toda la información del negocio. Responde el 80% de las consultas al instante. Las que no puede resolver las escala con el contexto completo. El tiempo de soporte bajó un 65%. La satisfacción subió. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["80% RESUELTO", "-65% SOPORTE", "SATISFACCIÓN SUBE", "IA REAL"],
        "hashtags": ["#inteligenciaartificial", "#atencioncliente", "#chatbot", "#pymesespana", "#ziautomate"],
        "engagement_question": "¿Cuánto tiempo dedica tu equipo a responder preguntas repetitivas cada día?",
    },
    {
        "topic": "3 automatizaciones para empezar hoy mismo",
        "script": "Si solo pudieras hacer 3 cosas para automatizar tu negocio esta semana, haz estas. Una: respuesta automática a cualquier contacto nuevo en menos de 5 minutos. Dos: recordatorio de cita 24 horas antes. Tres: mensaje automático a clientes que llevan 30 días sin comprarte. Estas tres generan más impacto que cualquier otra inversión que puedas hacer ahora mismo. La mayoría de negocios ven resultados en menos de 2 semanas. ¿Empezamos? Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["3 AUTOMATIZACIONES", "5 MINUTOS RESP.", "2 SEMANAS", "EMPEZAMOS HOY"],
        "hashtags": ["#automatizacion", "#productividadempresarial", "#pymesdigitales", "#transformaciondigital", "#ziautomate"],
        "engagement_question": "¿Por cuál de estas tres empezarías tú?",
    },
    {
        "topic": "El gimnasio que venció la fuga de enero a marzo",
        "script": "Enero es el mejor mes para un gimnasio. Marzo es el peor. Cada año igual. Un gimnasio en Alicante perdía 40 socios cada primavera sin poder hacer nada. Ahora cuando un socio lleva 10 días sin entrar, el sistema le manda automáticamente un mensaje con motivación y una sesión gratis con entrenador. Las bajas bajaron un 25% en 2 meses. El dueño no persigue a nadie. El sistema lo hace por él. Los 12 meses del año. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["40 BAJAS/MES", "-25% EN 2 MESES", "10 DÍAS SIN ENTRAR", "VUELVEN SOLOS"],
        "hashtags": ["#gimnasio", "#automatizacion", "#fidelizacion", "#gestionclientes", "#ziautomate"],
        "engagement_question": "¿Tu negocio tiene algún sistema para recuperar clientes que llevan tiempo sin volver?",
    },
    {
        "topic": "Los chatbots de IA de ahora no son los de antes",
        "script": "Los chatbots de hace 5 años eran una vergüenza. Guiones rígidos que irritaban a cualquier cliente. Los de ahora son completamente distintos. Entienden lenguaje natural. Conocen tu negocio en profundidad. Están disponibles los 365 días a cualquier hora. Una ferretería en Toledo atiende ahora 200 consultas al día sin contratar a nadie más. El dueño solo interviene cuando hay que cerrar una venta grande. Todo lo demás lo gestiona el bot. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["200 CONSULTAS/DÍA", "365 DÍAS", "SIN CONTRATAR", "CHATBOT REAL"],
        "hashtags": ["#chatbot", "#inteligenciaartificial", "#atencioncliente", "#pymesespana", "#ziautomate"],
        "engagement_question": "¿Tienes chatbot en tu negocio o todavía gestionas todas las consultas a mano?",
    },
    {
        "topic": "La automatización se paga sola en el primer mes",
        "script": "¿Cuánto cuesta automatizar tu negocio? Entre 300 y 600 euros montar un sistema básico. ¿Cuánto te devuelve? Haz el cálculo: si ese sistema te trae 2 clientes al mes que antes se perdían y cada cliente vale 200 euros, el primer mes ya recuperaste la inversión. A partir del segundo mes es beneficio puro. Todos los meses. Sin hacer nada extra. La pregunta real no es si puedes permitirte hacerlo. Es si puedes permitirte seguir sin hacerlo. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["300-600€", "MES 1 AMORTIZADO", "BENEFICIO PURO", "¿PUEDES NO HACERLO?"],
        "hashtags": ["#automatizacion", "#roi", "#inversion", "#pymesespana", "#ziautomate"],
        "engagement_question": "¿Has calculado cuánto dinero te cuesta al mes no tener automatizado tu negocio?",
    },
    {
        "topic": "El canal de marketing que nadie en España usa bien",
        "script": "El canal con mejor retorno de inversión en marketing digital no es Instagram. No es Google. Es el email. Y casi nadie en España lo está usando bien. Lo que montamos son secuencias automáticas: alguien se apunta a tu lista y durante 2 semanas recibe emails que le llevan de no conocerte a querer comprarte. Sin que escribas nada nuevo. Una tienda de suplementos genera 3.000 euros al mes solo con la secuencia de bienvenida. Siempre activa. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["MAYOR RETORNO", "3.000€/MES", "SIEMPRE ACTIVO", "EMAIL MARKETING"],
        "hashtags": ["#emailmarketing", "#automatizacion", "#marketingdigital", "#ventasonline", "#ziautomate"],
        "engagement_question": "¿Estás usando el email marketing en tu negocio o lo tienes todavía pendiente?",
    },
    {
        "topic": "Toma decisiones con datos, no con el estómago",
        "script": "La mayoría de dueños de negocio toman sus decisiones con el estómago. Suben precios porque intuyen que pueden. Lanzan productos porque les parece buena idea. Y luego se preguntan por qué no funciona. Una tienda de moda online descubrió con IA que el 70% de sus ventas venían del 15% de sus productos. Eliminó el resto. Dobló el margen neto. No porque fuera más lista. Sino porque por fin tomó decisiones con datos reales. Escríbeme o entra en ziautomate.netlify.app",
        "highlights": ["DATOS REALES", "70% EN 15%", "DOBLE MARGEN", "DECIDE MEJOR"],
        "hashtags": ["#analisisdedatos", "#inteligenciaartificial", "#decisionesempresariales", "#pymesespana", "#ziautomate"],
        "engagement_question": "¿Tomas las decisiones de tu negocio con datos o con intuición?",
    },
]
