TEMAS = [
    "Cómo automatizar el seguimiento de clientes y no perder ninguno",
    "5 tareas que puedes automatizar en tu negocio esta misma semana",
    "Qué es n8n y cómo te ahorra 10 horas a la semana",
    "Cómo crear un chatbot para tu negocio sin saber programar",
    "Automatiza tus publicaciones de Instagram con IA y olvídate",
    "Cómo conectar tu web con WhatsApp automáticamente",
    "Qué es Make y cómo funciona para automatizar tu negocio",
    "Captura leads automáticamente sin hacer nada",
    "Cómo enviar emails automáticos cuando alguien contacta contigo",
    "La diferencia entre automatización e inteligencia artificial",
    "Cómo una inmobiliaria consiguió el doble de contactos con IA",
    "Automatiza tu agenda de citas y nunca más hagas nada a mano",
    "Cómo responder a clientes en segundos con un bot de IA",
    "Por qué tu competencia ya está usando automatización y tú no",
    "Cómo ahorrar 20 horas al mes con estas 3 automatizaciones",
    "Qué es Airtable y cómo organiza tu negocio automáticamente",
    "Cómo generar facturas automáticamente sin tocar nada",
    "El futuro de los negocios: IA trabajando mientras tú duermes",
    "Cómo un restaurante automatizó sus reservas con IA",
    "Conecta tu tienda online con tu almacén automáticamente",
    "Cómo hacer seguimiento de ventas sin una hoja de Excel",
    "Automatización para clínicas: citas, recordatorios y más",
    "Qué es Zapier y en qué se diferencia de Make y n8n",
    "Cómo enviar propuestas a clientes automáticamente",
    "3 automatizaciones que todo negocio debería tener ya",
    "Cómo tu negocio puede funcionar 24 horas sin empleados extra",
    "Qué es un CRM y cómo automatizarlo con IA",
    "Cómo generar contenido para redes sociales con IA cada día",
    "Automatiza los pedidos de tu tienda y reduce errores al 0",
    "Cómo la IA puede atender a tus clientes mejor que tú",
]
